-- ----------------------------
-- 21、自动报表任务表
-- ----------------------------
DROP TABLE IF EXISTS MONI_EXPORT;
CREATE TABLE MONI_EXPORT (
  ID INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  ASID VARCHAR(30) DEFAULT NULL COMMENT 'ASID',
  TICKET_NUMBER VARCHAR(20) DEFAULT NULL COMMENT 'TICKET NUMBER',
  EN_NAME VARCHAR(200) NOT NULL COMMENT '任务名称-英文',
  CH_NAME VARCHAR(200) NOT NULL COMMENT '任务名称-中文',
  STATUS CHAR(1) NOT NULL DEFAULT '1' COMMENT '状态（0正常 1停用）',
  JDBC CHAR(100) DEFAULT NULL COMMENT 'JDBC',
  PLATFORM CHAR(10) DEFAULT NULL COMMENT '平台',
  CRON_EXPRESSION VARCHAR(100) DEFAULT NULL COMMENT '频率',
  SCRIPT TEXT COMMENT 'SCRIPT',
  MAIL_TO VARCHAR(256) NOT NULL COMMENT '收件人',
  MAIL_CC VARCHAR(256) DEFAULT NULL COMMENT '收件人副本',
  MAIL_BCC VARCHAR(256) DEFAULT NULL COMMENT '收件人密件副本',
  MAIL_SUBJECT VARCHAR(100) NOT NULL COMMENT '邮件主题',
  MAIL_CONTENT TEXT DEFAULT NULL COMMENT '邮件内容',
  CREATE_BY VARCHAR(30) NOT NULL COMMENT '建立人员',
  CREATE_TIME DATETIME NOT NULL COMMENT '建立时间',
  UPDATE_BY VARCHAR(30) DEFAULT NULL COMMENT '修改人员',
  UPDATE_TIME DATETIME DEFAULT NULL COMMENT '修改时间',
  REQUESTER VARCHAR(12) DEFAULT NULL COMMENT '请求者',
  LAST_EXPORT DATETIME DEFAULT NULL COMMENT '最后导出时间',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='自动报表任务表';


-- ----------------------------
-- 22、SQL检测任务LOG表
-- ----------------------------
DROP TABLE IF EXISTS MONI_EXPORT_LOG;
CREATE TABLE MONI_EXPORT_LOG (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  EXPORT_ID INT(11) NOT NULL COMMENT '任务ID',
  START_TIME DATETIME DEFAULT NULL COMMENT '开始时间',
  END_TIME DATETIME DEFAULT NULL COMMENT '结束时间',
  FILE_NAME TEXT COMMENT '文件名称',
  EXCEPTION_LOG TEXT COMMENT '异常信息',
  EXECUTE_TIME INT(11) DEFAULT 0 COMMENT '执行时长(秒)',
  STATUS VARCHAR(1) DEFAULT NULL COMMENT '执行状态（0成功 1失败 2错误）',
  OPERATOR VARCHAR(30) DEFAULT NULL COMMENT '操作者,系统则为system',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='自动报表任务LOG表';
