#项目相关配置
as:
    # 实例演示开关
    demoEnabled: true
    # 文件路径 示例（ Windows配置D:/as/uploadPath，Linux配置 /home/as/uploadPath）
    #所有文件都会保存在里面(telegram photo、export excel等)，路径不存在会自动创建，不需要手工创建
    profile: D:/as/uploadPath
    # 项目域名(仅在telegram推送告警时使用，别无他用)
    asDomain: http://127.0.0.1

elastic:
    #pf1
    pf1:
        #url
        url: 172.26.101.48
        #端口
        port: 9200
    #pf2
    pf2:
        #url
        Url: 172.26.113.95
        #端口
        port: 9200


# 开发环境配置
server:
    # 服务器的HTTP端口，默认为80
    port: 80
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # tomcat最大线程数，默认为200
        max-threads: 800
        # Tomcat启动初始化的线程数，默认值25
        min-spare-threads: 30

# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # AS Portal mysql dev
            master:
                url: jdbc:mysql://192.168.247.128:3306/monitor?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: abc123123
                driverClassName: com.mysql.cj.jdbc.Driver
            # pf1 lottery dev
            pf1:
                # pf1 lottery
                main:
                    # enabled 数据源开关
                    enabled: true
                    url: jdbc:oracle:thin:@DB.PF1DEV1-OOB.COM:1521/lottery
                    username: lott_new_a3d1
                    password: 2wsxzaq1
                    driverClassName: oracle.jdbc.driver.OracleDriver
                # pf1 lottery sec
                sec:
                    # enabled 数据源开关
                    enabled: true
                    url: jdbc:oracle:thin:@DB.PF1DEV1-OOB.COM:1521/lottery
                    username: lott_new_a3d1
                    password: 2wsxzaq1
                    driverClassName: oracle.jdbc.driver.OracleDriver
            # pf2 core dev
            pf2-core:
                # pf2 core
                main:
                    # enabled 数据源开关
                    enabled: true
                    url: jdbc:oracle:thin:@DB.PF2DEV1-OOB.COM:1521/UB8.pf2dev1.com
                    username: core
                    password: core
                    driverClassName: oracle.jdbc.driver.OracleDriver
                # pf2 core sec
                sec:
                    # enabled 数据源开关
                    enabled: true
                    url: jdbc:oracle:thin:@DB.PF2DEV1-OOB.COM:1521/UB8.pf2dev1.com
                    username: core
                    password: core
                    driverClassName: oracle.jdbc.driver.OracleDriver
            # pf2 draw dev
            pf2-draw:
                # enabled 数据源开关
                enabled: true
                url: jdbc:oracle:thin:@DB.PF2DEV1-OOB.COM:1521/UB8.pf2dev1.com
                username: core
                password: core
                driverClassName: oracle.jdbc.driver.OracleDriver
            # pf2 dw dev
            pf2-dw:
                # enabled 数据源开关
                enabled: true
                url: jdbc:oracle:thin:@DWDB.PF2DEV1-OOB.COM:1521/DW.pf2dev1.com
                username: AS_MONITOR
                password: BBdsk_1720ij
                driverClassName: oracle.jdbc.driver.OracleDriver


            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: admin
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true